### ISSUE TITLE
Timer example for periodic task

### ISSUE THREAD

**Issue by wbadry** [hpssjellis/my-examples-for-the-arduino-portentaH7#1]
Hi,
Is there any working example for using timer event to carry any task such as serial write or even toggling an LED?

Thanks

**Comment by hpssjellis** [comment]
Hmmm, mBED or any Arduino timer should work on the Portenta. I probably have an example that uses timers. give me a minute.

**Comment by hpssjellis** [comment]
Not the easiest timer example, but this one has a timer so that the onboard LED can be manipulated

https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/blob/master/my06_LED_onboard_setRGB.ino

**Comment by wbadry** [comment]
Thank you so much. This is a software inaccurate timing mechanism. I was looking for hardware timer interrupt. I believe I'll use Threaded Timer for now that is the closest to what Inwish for. Thanks again

**Comment by hpssjellis** [comment]
Sounds interesting send a link if it works. Not sure if this is related, but I was looking into the real time clock on the Portenta but I don't think there is any Arduino code MBED might have some code for it. 

I mention this on the Portenta [Facebook group](https://www.facebook.com/groups/portenta/permalink/728539591133919/).

**Comment by wbadry** [comment]
Hi @hpssjellis 

I created a hasty example but would demonstrate the concept using a threaded library which is based on mbed OS threading.


```cpp
/**
* Blinking example using threaded timer 
* By  : Waleed El-Badry
* Date: 20/02/2021
**/

// Threaded timer library: https://github.com/Aduen/ThreadedTimer
#include <threadedtimer.h>


// Thread Object
ThreadedTimer t1;

// Task ID
int taskBlink;

// Blue LED on RGB
int led = LEDB;

// Variable to save last LED status
volatile bool led_status = true;


// Blinking routine
void blinking()
{
  digitalWrite(led, led_status);
  led_status = !led_status;
}

void setup() 
{

  // Set LED GPIO as output
  pinMode(led, OUTPUT);

  // Create blinking task to enter every blinking() routine every 500 ms
  taskBlink = t1.every(500, blinking);
  
}

void loop() 
{
  delay(2000); //main loop delay does not affect the running Timers
}
```

**Comment by hpssjellis** [comment]
Thanks so much for the example. I included it as you wrote it in the repository if that is OK with you?

[https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7#17](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7#17). I will also tweet about it using @rocksetta if that is also OK?
